version: '3.8'

services:
  comfyui:
    image: ${COMFYUI_IMAGE:-comfyui-rocm:local}
    build:
      context: .
      dockerfile: Dockerfile.cloudbuild
      args:
        PYTORCH_VERSION: ${PYTORCH_VERSION:-2.7.1}
        ROCM_VERSION: ${ROCM_VERSION:-6.4}
        UBUNTU_VERSION: ${UBUNTU_VERSION:-24.04}
    container_name: comfyui-rocm-6.4.4
    
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    
    ports:
      - "8188:8188"
    
    ipc: host
    shm_size: 8gb
    
    volumes:
      # Mount host ROCm 6.4.4
      - /opt/rocm:/opt/rocm:ro

      # ComfyUI directories
      - ./models:/app/models
      - ./output:/app/output
      - ./input:/app/input
      - ./custom_nodes:/app/custom_nodes
      - ./temp:/app/temp
      - ./workflows:/app/workflows

      # Setup scripts
      - ./container-setup.sh:/app/setup.sh:ro
    
    environment:
      - PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
      - LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64:$LD_LIBRARY_PATH
      - PATH=/opt/rocm/bin:$PATH
      - ROCM_PATH=/opt/rocm
      - MIGRAPHX_MLIR_USE_SPECIFIC_OPS=attention
      # Force RX 7900 XTX (gfx1100) compatibility
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - PYTORCH_ROCM_ARCH=gfx1100
      - HIP_VISIBLE_DEVICES=0
      - ROCR_VISIBLE_DEVICES=0
      - GPU_DEVICE_ORDINAL=0
      - HCC_AMDGPU_TARGET=gfx1100
      - AMDGPU_TARGETS=gfx1100
      - HSA_ENABLE_SDMA=0
    
    restart: unless-stopped
