name: Docker Hub Automated Build - ROCm 6.4.4 (Build Cloud)

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Rebuild weekly to get latest package updates
    - cron: '0 2 * * 1'  # Monday 2 AM UTC

env:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: comfyui-rocm

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx (Build Cloud)
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: "awaybreaktoday/github-public-away"
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=ubuntu24.04
          type=raw,value=pytorch2.7.1
          type=raw,value=rocm6.4.4
          type=raw,value=consumer-gpu
        labels: |
          org.opencontainers.image.title=ComfyUI AMD ROCm 6.4.4
          org.opencontainers.image.description=Stable Diffusion ComfyUI optimized for AMD GPUs with ROCm 6.4.4 support
          org.opencontainers.image.vendor=${{ secrets.VENDOR_NAME || github.repository_owner }}
          org.opencontainers.image.url=https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}/blob/main/docs/
          org.opencontainers.image.created=${{ steps.meta.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=GPL-3.0
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.cloudbuild
        platforms: ${{ matrix.platform }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PYTORCH_VERSION=2.7.1
          ROCM_VERSION=6.4
          UBUNTU_VERSION=24.04
          MAINTAINER_NAME=${{ secrets.MAINTAINER_NAME || 'ComfyUI ROCm Maintainer' }}
          MAINTAINER_EMAIL=${{ secrets.MAINTAINER_EMAIL || 'maintainer@example.com' }}
          VENDOR_NAME=${{ secrets.VENDOR_NAME || github.repository_owner }}
          IMAGE_VERSION=${{ steps.meta.outputs.version }}
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_USERNAME=${{ github.repository_owner }}
          GITHUB_REPO=${{ github.event.repository.name }}
          IMAGE_DESCRIPTION=${{ secrets.IMAGE_DESCRIPTION || 'ComfyUI with AMD ROCm 6.4.4 support - Lightweight container using host ROCm' }}
          IMAGE_URL=https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          SOURCE_URL=${{ github.server_url }}/${{ github.repository }}
          DOCUMENTATION_URL=${{ github.server_url }}/${{ github.repository }}/blob/main/docs/
          BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VCS_REF=${{ github.sha }}
        # For pull requests, export results to the build cache only
        # Otherwise, push to Docker Hub registry
        outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Update Docker Hub description
      # Only update description on main branch pushes, not PRs
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        readme-filepath: ./README.md

    - name: Output build info
      run: |
        echo "🏗️ Build completed with Docker Build Cloud!"
        echo "📋 Build Details:"
        echo "  Platform: ${{ matrix.platform }}"
        echo "  Event: ${{ github.event_name }}"
        echo "  Maintainer: ${{ secrets.MAINTAINER_NAME || 'ComfyUI ROCm Maintainer' }}"
        echo "  Vendor: ${{ secrets.VENDOR_NAME || github.repository_owner }}"
        echo "  Version: ${{ steps.meta.outputs.version }}"
        echo "  Repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
        echo "  Documentation: ${{ github.server_url }}/${{ github.repository }}/blob/main/docs/"
        echo "  Build Date: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}"
        echo "  VCS Ref: ${{ github.sha }}"
        echo "📦 Tags: ${{ steps.meta.outputs.tags }}"
        echo "🚀 Output: ${{ github.event_name == 'pull_request' && 'Cache Only (PR)' || 'Registry Push' }}"
